name = "ut-navi"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = ["nodejs_als"]
compatibility_date = "2026-06-01"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[observability]
enabled = true

[build]
command = "bun install --frozen-lockfile && bun run build"
